config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: 2.0.0
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    github.com/acoathena/aco_simuls:
      branch: main
      repo: https://github.com/acoathena/aco_simuls
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/acoathena/aco_simuls git:
        commands:
        - /usr/bin/env sh .sqa/script.dorky-olivine-coyote.sh
        container: qc.acc_wheezy-seashell-forest
  QC.Doc:
    repos:
      github.com/acoathena/aco_simuls find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.nippy-smalt-capybara.sh
        container: qc.doc_muggy-cream-loon
      github.com/acoathena/aco_simuls git:
        commands:
        - /usr/bin/env sh .sqa/script.clammy-denim-tetra.sh
        container: qc.doc_lumpy-goldenrod-grouse
      github.com/acoathena/aco_simuls markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.droopy-ultramarine-scorpion.sh
        container: qc.doc_frumpy-lime-opossum
  QC.Lic:
    repos:
      github.com/acoathena/aco_simuls licensee:
        commands:
        - /usr/bin/env sh .sqa/script.sloppy-amethyst-numbat.sh
        container: qc.lic_clammy-azure-lizard
  QC.Sec:
    repos:
      github.com/acoathena/aco_simuls bandit:
        commands:
        - /usr/bin/env sh .sqa/script.stinky-wisteria-echidna.sh
        container: qc.sec_flaky-pink-duck
  QC.Sty:
    repos:
      github.com/acoathena/aco_simuls flake8:
        commands:
        - /usr/bin/env sh .sqa/script.lousy-sangria-ragdoll.sh
        container: qc.sty_nerdy-violet-shrew
  QC.Uni:
    repos:
      github.com/acoathena/aco_simuls pytest:
        commands:
        - /usr/bin/env sh .sqa/script.chummy-alizarin-serval.sh
        container: qc.uni_skimpy-sangria-eleuth
  QC.Ver:
    repos:
      github.com/acoathena/aco_simuls get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.lanky-persimmon-gecko.sh
        container: qc.ver_pokey-burgundy-whippet
timeout: 5400
