config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: 2.0.0
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    github.com/acoathena/aco_simuls:
      branch: main
      repo: https://github.com/acoathena/aco_simuls
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/acoathena/aco_simuls git:
        commands:
        - /usr/bin/env sh .sqa/script.scanty-peach-hedgehog.sh
        container: qc.acc_surly-razzmatazz-lynx
  QC.Doc:
    repos:
      github.com/acoathena/aco_simuls find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.chewy-ochre-coyote.sh
        container: qc.doc_dorky-taupe-rhinoceros
      github.com/acoathena/aco_simuls git:
        commands:
        - /usr/bin/env sh .sqa/script.randy-pear-audemer.sh
        container: qc.doc_smelly-ultramarine-iguana
      github.com/acoathena/aco_simuls markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.homely-cerise-ant.sh
        container: qc.doc_blurry-aquamarine-dachsbracke
  QC.Lic:
    repos:
      github.com/acoathena/aco_simuls licensee:
        commands:
        - /usr/bin/env sh .sqa/script.stuffy-violet-beagle.sh
        container: qc.lic_goopy-alizarin-tarantula
  QC.Sec:
    repos:
      github.com/acoathena/aco_simuls bandit:
        commands:
        - /usr/bin/env sh .sqa/script.gimpy-chestnut-dachshund.sh
        container: qc.sec_muggy-charcoal-lobster
  QC.Sty:
    repos:
      github.com/acoathena/aco_simuls flake8:
        commands:
        - /usr/bin/env sh .sqa/script.jumpy-russet-hamster.sh
        container: qc.sty_hilly-lime-penguin
  QC.Uni:
    repos:
      github.com/acoathena/aco_simuls pytest:
        commands:
        - /usr/bin/env sh .sqa/script.randy-grey-dingo.sh
        container: qc.uni_silly-tan-lion
  QC.Ver:
    repos:
      github.com/acoathena/aco_simuls get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.sickly-zucchini-ostrich.sh
        container: qc.ver_tacky-ivory-bongo
timeout: 5400
