config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: 2.0.0
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    github.com/acoathena/aco_simuls:
      branch: main
      repo: https://github.com/acoathena/aco_simuls
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/acoathena/aco_simuls git:
        commands:
        - /usr/bin/env sh .sqa/script.boozy-tan-crocodile.sh
        container: qc.acc_grumpy-olive-bongo
  QC.Doc:
    repos:
      github.com/acoathena/aco_simuls find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.paltry-magenta-ocelot.sh
        container: qc.doc_sleepy-olive-starfish
      github.com/acoathena/aco_simuls git:
        commands:
        - /usr/bin/env sh .sqa/script.slaphappy-vermilion-bat.sh
        container: qc.doc_tasty-smalt-zebra
      github.com/acoathena/aco_simuls markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.nippy-chocolate-cougar.sh
        container: qc.doc_hilly-amaranth-mau
  QC.Lic:
    repos:
      github.com/acoathena/aco_simuls licensee:
        commands:
        - /usr/bin/env sh .sqa/script.freaky-mustard-impala.sh
        container: qc.lic_crabby-indigo-chinook
  QC.Sec:
    repos:
      github.com/acoathena/aco_simuls bandit:
        commands:
        - /usr/bin/env sh .sqa/script.blurry-ivory-lynx.sh
        container: qc.sec_homely-indigo-beetle
  QC.Sty:
    repos:
      github.com/acoathena/aco_simuls flake8:
        commands:
        - /usr/bin/env sh .sqa/script.stuffy-beige-shrimp.sh
        container: qc.sty_greasy-khaki-opossum
  QC.Uni:
    repos:
      github.com/acoathena/aco_simuls pytest:
        commands:
        - /usr/bin/env sh .sqa/script.homey-pumpkin-bombay.sh
        container: qc.uni_bumpy-carmine-burmese
  QC.Ver:
    repos:
      github.com/acoathena/aco_simuls get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.freaky-goldenrod-wasp.sh
        container: qc.ver_lousy-cream-termite
timeout: 5400
