config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: 2.0.0
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    github.com/acoathena/aco_simuls:
      branch: main
      repo: https://github.com/acoathena/aco_simuls
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/acoathena/aco_simuls git:
        commands:
        - /usr/bin/env sh .sqa/script.ready-linen-tapir.sh
        container: qc.acc_silly-magnolia-tamarin
  QC.Doc:
    repos:
      github.com/acoathena/aco_simuls find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.lumpy-tomato-mole.sh
        container: qc.doc_silly-firebrick-sheepdog
      github.com/acoathena/aco_simuls git:
        commands:
        - /usr/bin/env sh .sqa/script.lousy-yellow-antelope.sh
        container: qc.doc_breezy-maroon-antelope
      github.com/acoathena/aco_simuls markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.snappy-ivory-fossa.sh
        container: qc.doc_foggy-jade-squid
  QC.Lic:
    repos:
      github.com/acoathena/aco_simuls licensee:
        commands:
        - /usr/bin/env sh .sqa/script.blurry-periwinkle-wildebeest.sh
        container: qc.lic_flaky-charcoal-argentino
  QC.Sec:
    repos:
      github.com/acoathena/aco_simuls bandit:
        commands:
        - /usr/bin/env sh .sqa/script.boozy-blue-bonobo.sh
        container: qc.sec_scanty-smalt-eel
  QC.Sty:
    repos:
      github.com/acoathena/aco_simuls flake8:
        commands:
        - /usr/bin/env sh .sqa/script.tacky-seashell-discus.sh
        container: qc.sty_crabby-ultramarine-kangaroo
  QC.Uni:
    repos:
      github.com/acoathena/aco_simuls pytest:
        commands:
        - /usr/bin/env sh .sqa/script.clammy-cyan-lemming.sh
        container: qc.uni_snappy-rust-setter
  QC.Ver:
    repos:
      github.com/acoathena/aco_simuls get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.skinny-copper-dogfish.sh
        container: qc.ver_homey-maroon-paradise
timeout: 5400
