config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: 2.0.0
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    github.com/acoathena/aco_simuls:
      branch: main
      repo: https://github.com/acoathena/aco_simuls
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/acoathena/aco_simuls git:
        commands:
        - /usr/bin/env sh .sqa/script.nippy-teal-dhole.sh
        container: qc.acc_squeaky-silver-loon
  QC.Doc:
    repos:
      github.com/acoathena/aco_simuls find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.wimpy-pear-bear.sh
        container: qc.doc_foggy-rust-mule
      github.com/acoathena/aco_simuls git:
        commands:
        - /usr/bin/env sh .sqa/script.slimy-white-chimpanzee.sh
        container: qc.doc_muggy-yellow-affenpinscher
      github.com/acoathena/aco_simuls markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.zippy-burgundy-deer.sh
        container: qc.doc_smelly-fuchsia-tiger
  QC.Lic:
    repos:
      github.com/acoathena/aco_simuls licensee:
        commands:
        - /usr/bin/env sh .sqa/script.woolly-tangerine-fox.sh
        container: qc.lic_goopy-sepia-goat
  QC.Sec:
    repos:
      github.com/acoathena/aco_simuls bandit:
        commands:
        - /usr/bin/env sh .sqa/script.lousy-ochre-avocet.sh
        container: qc.sec_randy-azure-weasel
  QC.Sty:
    repos:
      github.com/acoathena/aco_simuls flake8:
        commands:
        - /usr/bin/env sh .sqa/script.shaggy-salmon-tapir.sh
        container: qc.sty_pasty-silver-fly
  QC.Uni:
    repos:
      github.com/acoathena/aco_simuls pytest:
        commands:
        - /usr/bin/env sh .sqa/script.baggy-orange-squirt.sh
        container: qc.uni_zippy-azure-dogfish
  QC.Ver:
    repos:
      github.com/acoathena/aco_simuls get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.skanky-purple-orangutan.sh
        container: qc.ver_slimy-plum-balinese
timeout: 5400
