config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: 2.0.0
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    github.com/acoathena/aco_simuls:
      branch: main
      repo: https://github.com/acoathena/aco_simuls
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/acoathena/aco_simuls git:
        commands:
        - /usr/bin/env sh .sqa/script.lovely-khaki-eagle.sh
        container: qc.acc_wheezy-chestnut-moose
  QC.Doc:
    repos:
      github.com/acoathena/aco_simuls find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.squeaky-celadon-gerbil.sh
        container: qc.doc_thirsty-lilac-goat
      github.com/acoathena/aco_simuls git:
        commands:
        - /usr/bin/env sh .sqa/script.clammy-firebrick-kangaroo.sh
        container: qc.doc_scummy-sepia-wolfhound
      github.com/acoathena/aco_simuls markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.lousy-viridian-ant.sh
        container: qc.doc_hilly-seashell-otter
  QC.Lic:
    repos:
      github.com/acoathena/aco_simuls licensee:
        commands:
        - /usr/bin/env sh .sqa/script.crappy-ochre-stoat.sh
        container: qc.lic_stinky-rust-collie
  QC.Sec:
    repos:
      github.com/acoathena/aco_simuls bandit:
        commands:
        - /usr/bin/env sh .sqa/script.homey-eggplant-rat.sh
        container: qc.sec_cheeky-flax-cattle
  QC.Sty:
    repos:
      github.com/acoathena/aco_simuls flake8:
        commands:
        - /usr/bin/env sh .sqa/script.clammy-ruby-crane.sh
        container: qc.sty_lanky-vermilion-budgerigar
  QC.Uni:
    repos:
      github.com/acoathena/aco_simuls pytest:
        commands:
        - /usr/bin/env sh .sqa/script.skanky-turquoise-orangutan.sh
        container: qc.uni_sunny-olivine-lemming
  QC.Ver:
    repos:
      github.com/acoathena/aco_simuls get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.trippy-malachite-uguisu.sh
        container: qc.ver_chewy-grey-gorilla
timeout: 5400
